"""Rename forths to fourths

Revision ID: 853fe6c6b21e
Revises: d2f8d30d4416
Create Date: 2025-12-14 22:00:15.018920

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '853fe6c6b21e'
down_revision = 'd2f8d30d4416'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fourths', sa.Integer(), nullable=True))
        batch_op.drop_column('forths')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.add_column(sa.Column('forths', sa.INTEGER(), nullable=True))
        batch_op.drop_column('fourths')

    # ### end Alembic commands ###
