"""Add new score columns

Revision ID: d2f8d30d4416
Revises: 
Create Date: 2025-11-16 17:41:36.780612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2f8d30d4416'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.add_column(sa.Column('firsts', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('seconds', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('thirds', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('forths', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.drop_column('forths')
        batch_op.drop_column('thirds')
        batch_op.drop_column('seconds')
        batch_op.drop_column('firsts')

    # ### end Alembic commands ###
